import './globals.css'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'NBA Fantasy League',
//   description: 'Generated by create next app',
// }
// used for keywords searches via google
// note: should not manually add <head> tags, instead refer to metadata API

export default function RootLayout({ children, }: { children: React.ReactNode; }) {
	return (
		<html lang="en" className="h-full bg-gray-200">
			<body className="h-full">
				{ children } 
			</body>
		</html>
	)
}
